---
title: "Signal and Noise Subgroups"
author: "Andrew Zimolzak"
date: "2022-10-09"
output: html_document
runtime: shiny
---

When a variable has no effect in most groups, but has an effect in one group,
it can look like no effect in the whole population.

```{r libraries, include=FALSE}
library(ggplot2)
library(dplyr)
library(shiny)
```

```{r functions, include=FALSE}
noisy_line <- function(slope, intercept, n, Subgroup) {
  
  n = n - 1
  
  data.frame(x = 0:n / n * 10, eps = rnorm(n + 1, 0, 1)) %>%
    mutate(y = slope * x + intercept + eps,
           Subgroup = Subgroup) -> df
  
  return(df)
  
}
```




## Settings

Choose how you want your populations to look.

```{r inputs, echo=FALSE}
inputPanel(
  # selectInput("do_subgroup", label = "Analyze high-risk only:",
  #             choices = c(TRUE, FALSE), selected = FALSE),

  sliderInput("nlow", label = "N of low-risk:",
              min = 50, max = 200, value = 100, step = 1),
  
  sliderInput("nmed", label = "N of medium-risk:",
              min = 50, max = 200, value = 100, step = 1),
  
  sliderInput("nhi", label = "N of high-risk:",
              min = 10, max = 40, value = 20, step = 1)
)
```


```{r function-plot, echo=FALSE}
make_rand_plot <- function(split_subgroups) {
  grp1 <- noisy_line(0, 3.5, input$nlow, 'Low risk')
  grp2 <- noisy_line(0, 6.5, input$nmed, 'Medium risk')
  grp3 <- noisy_line(1, 0, input$nhi, 'High risk')
  
  df <- rbind(grp1, grp2, grp3)
  
  if(split_subgroups) {
    df %>% filter(Subgroup == 'High risk') -> subg
    model <- lm(subg$y ~ subg$x)
    myplot <- ggplot(df, aes(x=x, y=y)) +
      geom_point(aes(color = Subgroup)) +
      geom_abline(slope = model$coefficients[2], intercept = model$coefficients[1])
  }
  else {
    model <- lm(df$y ~ df$x)
    myplot <- ggplot(df, aes(x=x, y=y)) +
      geom_point() +
      geom_abline(slope = model$coefficients[2], intercept = model$coefficients[1])
  }

  return(myplot)
}
```



```{r final, echo=FALSE}
renderPlot({
  make_rand_plot(split_subgroups = FALSE)
})

renderPlot({
  make_rand_plot(split_subgroups = TRUE)
})

```

Testing `r reactive({input$nlow})` .
